import type { Metadata } from 'next'
import './globals.css'
import NavigationBar from '@/app/components/NavigationBar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body className='flex h-screen w-screen flex-col bg-gradient-to-br from-green-400 to-blue-600'>
                <NavigationBar />
                {children}
            </body>
        </html>
    )
}
