import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en' className='h-full'>
            <body className='h-full bg-gradient-to-br from-green-400 to-blue-600'>
                {children}
            </body>
        </html>
    )
}
